import { mountProfileEditor, validateProfilePoints } from './editors/profile/ProfileEditor.js';
import { mountSectionEditor, validateSection } from './editors/section/SectionEditor.js';
import { applyCageDelta, mountControlCageEditor } from './editors/cage/ControlCageEditor.js';

const i18n = { t: (_key, fallback) => fallback };
const model = {
  frontProfile: [{ id: 'p0', heightRatio: 0, halfExtentMm: 10 }, { id: 'p1', heightRatio: .5, halfExtentMm: 20 }, { id: 'p2', heightRatio: 1, halfExtentMm: 12 }],
  sideProfile: [{ id: 's0', heightRatio: 0, halfExtentMm: 8 }, { id: 's1', heightRatio: .5, halfExtentMm: 14 }, { id: 's2', heightRatio: 1, halfExtentMm: 9 }],
  crossSections: [{ id: 's-0', heightRatio: 0, widthMm: 20, depthMm: 16 }, { id: 's-1', heightRatio: .5, widthMm: 40, depthMm: 28 }, { id: 's-2', heightRatio: 1, widthMm: 24, depthMm: 18 }],
  controlCage: { nodes: [{ id: 'n1', positionMm: [10, 0, 0] }, { id: 'n2', positionMm: [20, 0, 0], pinned: true }], edges: [{ from: 'n1', to: 'n2' }] },
};

function root() { document.body.innerHTML = '<div id="root"></div>'; return document.getElementById('root'); }
function rect(node, width = 420, height = 300) { node.getBoundingClientRect = () => ({ left: 0, top: 0, width, height, right: width, bottom: height }); }
function pointer(node, type, x, y, options = {}) { const event = new MouseEvent(type, { bubbles: true, clientX: x, clientY: y, ...options }); Object.defineProperty(event, 'pointerId', { value: 1 }); node.dispatchEvent(event); }

test('profile validation accepts ordered finite profile', () => expect(validateProfilePoints(model.frontProfile).valid).toBe(true));
test('profile validation rejects duplicate heights', () => expect(validateProfilePoints([{ heightRatio: 0, halfExtentMm: 1 }, { heightRatio: 0, halfExtentMm: 1 }, { heightRatio: 1, halfExtentMm: 1 }]).valid).toBe(false));
test('profile drag creates one dirty event and changes model point', () => { const dirty = jest.fn(); const editor = mountProfileEditor(root(), { i18n, model, onDirty: dirty }); const svg = document.querySelector('svg'); rect(svg); const node = document.querySelector('[data-profile-point-id="p1"]'); pointer(node, 'pointerdown', 220, 150); pointer(svg, 'pointermove', 410, 120); pointer(window, 'pointerup', 410, 120); expect(editor.getPoints().find((item) => item.id === 'p1').halfExtentMm).toBeGreaterThan(20); expect(dirty).toHaveBeenCalled(); });
test('profile insertion keeps stable existing IDs', () => { const editor = mountProfileEditor(root(), { i18n, model }); document.querySelector('[data-profile-point-id="p1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); document.querySelectorAll('button')[2].click(); expect(editor.getPoints().map((item) => item.id)).toEqual(expect.arrayContaining(['p0', 'p1', 'p2'])); });
test('profile delete is blocked below minimum point count', () => { const editor = mountProfileEditor(root(), { i18n, model: { ...model, frontProfile: model.frontProfile } }); document.querySelector('[data-profile-point-id="p1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); document.querySelectorAll('button')[3].click(); expect(editor.getPoints()).toHaveLength(3); });
test('profile undo and redo restore a drag', () => { const editor = mountProfileEditor(root(), { i18n, model }); const svg = document.querySelector('svg'); rect(svg); const node = document.querySelector('[data-profile-point-id="p1"]'); pointer(node, 'pointerdown', 220, 150); pointer(svg, 'pointermove', 410, 120); pointer(window, 'pointerup', 410, 120); const changed = editor.getPoints()[1].halfExtentMm; document.querySelectorAll('button')[6].click(); expect(editor.getPoints()[1].halfExtentMm).toBe(20); document.querySelectorAll('button')[7].click(); expect(editor.getPoints()[1].halfExtentMm).toBe(changed); });
test('profile apply refuses invalid state', async () => { const apply = jest.fn(); const editor = mountProfileEditor(root(), { i18n, model, onApply: apply }); expect(editor.getValidation().valid).toBe(true); document.querySelector('[data-profile-point-id="p1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); document.querySelectorAll('button')[3].click(); expect(editor.getValidation().valid).toBe(true); await Promise.resolve(); expect(apply).not.toHaveBeenCalled(); });
test('profile tangent handle is rendered for selected point', () => { mountProfileEditor(root(), { i18n, model }); document.querySelector('[data-profile-point-id="p1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); expect(document.querySelector('[data-tangent-for="p1"]')).not.toBeNull(); });
test('section validation rejects a non-positive dimension', () => expect(validateSection({ widthMm: 0, depthMm: 10, points: [] }).valid).toBe(false));
test('section editor renders a closed loop from generic points', () => { const sections = [{ id: 's-1', heightRatio: .5, widthMm: 20, depthMm: 20, points: Array.from({ length: 8 }, (_, i) => ({ id: `p${i}`, xMm: Math.cos(i) * 10, zMm: Math.sin(i) * 10 })) }]; mountSectionEditor(root(), { i18n, model: { ...model, crossSections: sections } }); expect(document.querySelector('[data-section-loop="s-1"]')).not.toBeNull(); expect(document.querySelectorAll('[data-section-point-id]').length).toBe(8); });
test('section point drag changes a real loop point', () => { const editor = mountSectionEditor(root(), { i18n, model }); const svg = document.querySelector('svg'); rect(svg, 360, 300); const point = document.querySelector('[data-section-point-id]'); pointer(point, 'pointerdown', 190, 120); pointer(svg, 'pointermove', 250, 100); pointer(window, 'pointerup', 250, 100); expect(editor.getSections()[1].points.some((item) => Math.abs(item.xMm) > 10)).toBe(true); });
test('section list selection changes active ID', () => { const editor = mountSectionEditor(root(), { i18n, model }); const list = document.querySelector('select'); list.value = 's-0'; list.dispatchEvent(new Event('change')); expect(editor.getSelectedId()).toBe('s-0'); });
test('section add creates stable ID and loop points', () => { const editor = mountSectionEditor(root(), { i18n, model }); document.querySelectorAll('button')[1].click(); expect(editor.getSections().at(-1).points.length).toBe(16); });
test('section duplicate copies loop with new point IDs', () => { const editor = mountSectionEditor(root(), { i18n, model }); document.querySelectorAll('button')[2].click(); const sections = editor.getSections(); expect(new Set(sections.at(-1).points.map((item) => item.id)).size).toBe(16); });
test('section falloff cycles local medium wide', () => { const editor = mountSectionEditor(root(), { i18n, model }); document.querySelectorAll('button')[4].click(); expect(editor.getFalloff()).toBe('wide'); });
test('section undo restores a deleted section', () => { const editor = mountSectionEditor(root(), { i18n, model }); document.querySelectorAll('button')[2].click(); expect(editor.getSections()).toHaveLength(3); document.querySelectorAll('button')[5].click(); expect(editor.getSections()).toHaveLength(3); });
test('cage delta leaves pinned nodes unchanged', () => { const result = applyCageDelta(model.controlCage.nodes, ['n2'], [10, 0, 4]); expect(result[1].positionMm).toEqual([20, 0, 0]); });
test('cage delta respects locked axis', () => { const result = applyCageDelta([{ id: 'n', positionMm: [1, 2, 3], lockedAxes: ['x'] }], ['n'], [4, 5, 6]); expect(result[0].positionMm).toEqual([1, 7, 9]); });
test('cage editor renders edges with object edge IDs', () => { mountControlCageEditor(root(), { i18n, cage: model.controlCage }); expect(document.querySelectorAll('line').length).toBe(1); expect(document.querySelectorAll('[data-cage-node-id]').length).toBe(2); });
test('cage shift pointer selection selects multiple nodes', () => { mountControlCageEditor(root(), { i18n, cage: model.controlCage }); const nodes = document.querySelectorAll('[data-cage-node-id]'); nodes[0].dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); nodes[1].dispatchEvent(new MouseEvent('mousedown', { bubbles: true, shiftKey: true })); expect(document.querySelector('.interactive-editor__status').textContent).toContain('Selected: 2'); });
test('cage pin operation changes persistent node state', () => { const editor = mountControlCageEditor(root(), { i18n, cage: model.controlCage }); document.querySelector('[data-cage-node-id="n1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); document.querySelectorAll('button')[2].click(); expect(editor.getNodes().find((item) => item.id === 'n1').pinned).toBe(true); });
test('cage reset restores rest position', () => { const editor = mountControlCageEditor(root(), { i18n, cage: { ...model.controlCage, nodes: [{ id: 'n1', positionMm: [20, 0, 0], restPositionMm: [10, 0, 0] }] } }); document.querySelector('[data-cage-node-id="n1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); document.querySelectorAll('button')[3].click(); expect(editor.getNodes()[0].positionMm).toEqual([10, 0, 0]); });
test('cage undo restores exact node position', () => { const editor = mountControlCageEditor(root(), { i18n, cage: model.controlCage }); const svg = document.querySelector('svg'); rect(svg); const node = document.querySelector('[data-cage-node-id="n1"]'); pointer(node, 'pointerdown', 180, 150); pointer(svg, 'pointermove', 240, 140); pointer(window, 'pointerup', 240, 140); document.querySelectorAll('button')[4].click(); expect(editor.getNodes()[0].positionMm).toEqual([10, 0, 0]); });
test('cage apply emits source editor metadata', async () => { const apply = jest.fn(); mountControlCageEditor(root(), { i18n, cage: model.controlCage, onApply: apply }); document.querySelector('[data-cage-node-id="n1"]').dispatchEvent(new MouseEvent('mousedown', { bubbles: true })); document.querySelectorAll('button')[6].click(); await Promise.resolve(); expect(apply).toHaveBeenCalledWith(expect.objectContaining({ sourceEditor: 'control-cage' })); });
test('profile apply emits source editor metadata', async () => { const apply = jest.fn(); mountProfileEditor(root(), { i18n, model, onApply: apply }); document.querySelectorAll('button')[8].click(); await Promise.resolve(); expect(apply).toHaveBeenCalledWith(expect.objectContaining({ sourceEditor: 'profile' })); });
test('section apply emits source editor metadata', async () => { const apply = jest.fn(); mountSectionEditor(root(), { i18n, model, onApply: apply }); document.querySelectorAll('button')[7].click(); await Promise.resolve(); expect(apply).toHaveBeenCalledWith(expect.objectContaining({ sourceEditor: 'section' })); });
